### ISSUE TITLE
CoffeeScript vimrc code raises an error and doesn't work

### ISSUE THREAD

**Issue by lukgreen** [majutsushi/tagbar#259]
The vimrc code given as an alternative to CoffeeTags raises an error: `E54: Unmatched (`
Because of this or some other reason the TagBar panel stays empty ("No tags found") while working on CoffeeScript files.
I wonder if the code works fine for anyone?

Correcting `'\v\\([nst]\)'` to `'\v\\([nst])'` in the last line eliminates the "Unmatched" error but TagBar still doesn't find any tags.

**Comment by majutsushi** [comment]
Okay, I don't know what the original author was trying to accomplish with that substitution, but there were some quoting issues. If you put the configuration into the standard `~/.ctags` file instead of a Vim variable then it will work (at least it does for me). I've modified the Wiki to reflect that.
