### ISSUE TITLE
New filetype works via ctags, but not TagBar

### ISSUE THREAD

**Issue by cbates-** [majutsushi/tagbar#265]
In ctags.cnf:   
> --langdef=inifile
> --langmap=inifile:.ini
> --regex-inifile=/^[([a-zA-Z0-9_-]+)]/\1/s,section/  

In vimrc:  
> let g:tagbar_type_ini = {
> \ 'ctagstype' : 'inifile',
> \ 'kinds' : [
> \ 's:section'
> \ ]
> \ }

If I generate a tags file from a .ini file, I get entries that look like this:  

> BatchMaker .\watcher.ini /^[BatchMaker]$/;" s

If I set this tags file as current, then  
*:ts /Batch*   
works as expected, allowing me to navigate to the BatchMaker section in the .ini file.

However, TagBar does not work with this config.
What am I doing wrong? Is there a way to 'debug' TagBar's processing?

Thanks for TagBar, I use it every day...

**Comment by majutsushi** [comment]
There is a way to enable debugging, have a look at ':h tagbar-issues'.
However, the problem is most likely that the Vim filetype doesn't match your
Tagbar configuration. By default Vim uses the filetype 'dosini' for .ini
files (you can check with ':set ft?'), but you have set up Tagbar to look for
filetype 'inifile'. If you change your variable name to 'g:tagbar_type_dosini'
it will probably work.

**Comment by cbates-** [comment]
Thanks for the quick reply. Made the change to 'g:tagbar_type_dosini', and after some tinkering with the regex at the command line tagbar is working as desired in vim.
Very useful.
