### ISSUE TITLE
Dashes in shell functions not recognized

### ISSUE THREAD

**Issue by blueyed** [majutsushi/tagbar#275]
Given the following `test.sh` file, `:TagbarCurrentTag fs` does not recognize the tag, with the cursor at ":":

```
_git-cherry () {
  :
}
```

Please note that the function itself shows up in the tags file with `ctags -f- /tmp/test.sh` (I am using [universal-ctags](https://github.com/universal-ctags/ctags), where this has been fixed in https://github.com/universal-ctags/ctags/issues/164):

```
_git-cherry /tmp/test.sh    /^_git-cherry () {$/;"  f   language:Sh
```

**Comment by majutsushi** [comment]
This seems to work for me, so something seems to have fixed it in the
meantime. Or are you still seeing it?

**Comment by joseluis** [comment]
Functions with dashes are not recognized for me either. Using vim 8.0 and latest tagbar.

Using @blueyed's example, if I replace the dash with another character then it does get recognized by tagbar.

And other valid characters for Bash function names doesn't get recognized either, like colons. It seems this plugin is only giving validity to alphanumeric charactesr plus underscore.

This means for me that I can't use this plugin at all, since I'm always using dashes and colons for bash functions, like this:

```bash
namespace::function-name() {
    :
}
```

**Comment by majutsushi** [comment]
Good to know, thanks. I'm going to close this then.
