### ISSUE TITLE
After installing vim, ctags, pathogen, vim-go and tagbar, no tags found

### ISSUE THREAD

**Issue by koebi** [majutsushi/tagbar#286]
I just installed a fresh vim and ctags from debian, a fresh pathogen, vim-go and tagbar as told on the gh-readmes, opened a go file, issued :TagbarOpen and got "no tags found" in the upcoming tagbar. 

I got this working, but then tried something with setting the fold level automatically. Afterwards, it didn't work anymore…

If I can provide any logs, info etc, just let me know :))

**Comment by sbdchd** [comment]
I am just spitballing but does the tested go program successfully compile?

**Comment by Zanadar** [comment]
I had this issue too and it indeeed does look like it's related to the unsuccessful building of the package.
Before, package was broken, no tags. After I fixed the build, tags.

**Comment by majutsushi** [comment]
Since this sounds like an issue with the tags-generating program I'm going to close this for now. If the program does successfully generate the tags but they don't show up in Tagbar then please reopen this issue and provide a log file as described in `:h tagbar-issues`.

**Comment by neooelric** [comment]
hi..

this issue just reappeared on my laptop.

here is the step:

1: windows 7, my home directory path is "C:\Users\zhangshaobo"
2: install gvim from "gvim80-586.exe". to a custom destination "D:\program"
3: download "plug.vim" from "https://github.com/junegunn/vim-plug"
4: create directory "D:\program\Vim\vimfiles\autoload"， put "plug.vim" mentioned in above in this directory
5: create file "~/_vimrc", the content is as below, this file will be in attachments.
6: open gvim.exe, type ":PlugStatus" check the plugins I wanted. The three plugins I wanted is vim-go, neocomplete.vim, tagbar....... vim-plug tell me all plugins ain't install yet, so i type ":PlugInstall" to install them
7: after vim-go was installed, I type "GoInstallBinaries" to install all these binary programs vim-go needed. included "gotags". By the way my $GOPATH is "~/go", and GOPATH is the only system-env-variable I set after i install Golang from offical MSI installer(go1.8.windows-amd64.mis).  
8: in order to use Tagbar, I downloaded "ctags58.zip" from "http://ctags.sourceforge.net/", extract it into "D:\program"
9: then i did something to "~/_vimrc", like set the g:tagbar_ctags_bin, g_tagbar_type_go etc.. 

After all, Tagbar should be works. actually it did, but just for C files.
Once i open an Golang file, it just tell me " No tags found."

First I thought maybe is the $GOPATH/bin/gotags.exe wrong or broken. 
but test from cmd or powershell, this binary seems all right.
then I reinstall gotags...... doesn't work ... sadly once

Second I thought mybe is the path of gotags.exe was too long or sth wrong. 
then I pick the "gotags.exe" file, copy it into "D:\program".
and modify the coresspond content in "~/_vimrc".
test D:\program\gotags.exe from cmd & powershell, works!
in gvim! noop! ...... sadly twice.

through all of my trying shot, Tagbar working coreectly for C files from beginning to ends.

I use the tool ":TagbarDebug" generate the logfile of "for C file, works!" and "for Go files, noop!"

these log files also in attachments too.
I read these log file, seems Tagbar run ctags.exe or gtags.exe in the temp file in ~/AppData/Local/Temp instead of the original source file.
the temp file should be a temp copy of source file i guess. according the log file, the temp file coressponding to Go source file may be empty.

[attachements.zip](https://github.com/majutsushi/tagbar/files/992461/attachements.zip)

**Comment by majutsushi** [comment]
According to your logfiles Tagbar seems to do execute the gotags program correctly, but the resulting tags file is empty. This looks like an issue with the tags program to me. Does it actually generate tags when you run it on the command line, even when you execute it with the same options?

**Comment by neooelric** [comment]
I'm pretty sure the gotags program execute correctlly. I've tried many times.

I notice that when tagbar calls gotags, gotags actually was analysising a temp file(in ~/AppData/Local/Temp/) instead of the source file itself. and when calls over, this temp file was gone, seems like deleted by tagbar.
Maybe because this temp file was an empty file. I donnt know, just guess.

**Comment by neooelric** [comment]
thanks for reply. my english is not good. if you still cannot figure out what was happened from my comments. maybe i can  try to make a screen recording or something else to show you what happened.

**Comment by majutsushi** [comment]
Yes, Tagbar uses a temporary file instead of the original file for processing. This way it is possible to process files that are loaded through netrw, and to avoid delays in case the original file is on a network drive.

You could inspect the tempfile by commenting out [this line](https://github.com/majutsushi/tagbar/blob/959f48798136bfd4ce60075d3c86c580fcf5e5c5/autoload/tagbar.vim#L2282) locally and then running gotags manually on it to see what result you get.
