### ISSUE TITLE
Confused about sorting order

### ISSUE THREAD

**Issue by pitchforks** [majutsushi/tagbar#287]
Tagbar docs say:

> - Tags can be sorted either by name or order of appearance in the file.

Should I read "tags file" here or actual "source code" file?

Asking because I'm using latest master (https://github.com/majutsushi/tagbar/commit/7b36c46d17d57db34fdb0adac9ba6382d0bb5e66) and for this simple Python file:

    def myfunc():
        pass

    class MyClass:
        pass

the order of tags in the Tagbar window does not change when I hit s to toggle sort order - `myfunc` always appears below `MyClass`.

**Comment by blueyed** [comment]
Confirmed.

**Comment by majutsushi** [comment]
That's because `myfunc()` is a function, while `MyClass` is a class. The sort order only applies within the same type of tag, or "kind" as ctags calls it. And by default classes are sorted before functions in Python.

This can be changed by modifying the configuration for Python as explained in `:h tagbar-extend`.
