### ISSUE TITLE
Not efficient enough when navigating tags in Tagbar window

### ISSUE THREAD

**Issue by tamlok** [majutsushi/tagbar#304]
I tried Tagbar today on OpenSUSE 42.1 with Gnome. I found it not efficient when navigating tags using `j` and `k` in Tagbar window. The file I was editing was `arch/x86/kvm/x86.c` in Linux kernel tree with about 7987 lines. I felt like dragging it obviously when pressing `j` continually.
It is said that Tagbar creates the tag on-the-fly. So maybe this is the cause?
Great plugin anyway!
Thanks very much!

**Comment by majutsushi** [comment]
This doesn't look like a Tagbar issue to me. Tagbar doesn't actually run anything when you move the cursor in its window with `j` or `k` (unless you have `g:tagbar_autopreview` set). I noticed a bit of sluggishness with that file if I had the `cursorline` option set, but without that everything was very fast. So this is most likely caused by something else.
