### ISSUE TITLE
Tagbar doesn't recognize static functions in C file

### ISSUE THREAD

**Issue by gahcep** [majutsushi/tagbar#314]
Hi,

I noticed a weird behavior when was going through one C file. The following function is recognized:

`int AppHandler_RegisterSensor(void)`

whereas this one is not:

`static int AppHandler_RegisterSensor(void)`

Could you please check this?

**Comment by hgiesel** [comment]
I also noticed this. I remember this working just fine.

**Comment by rjayatilleka** [comment]
Same problem.

**Comment by majutsushi** [comment]
Are you using Universal Ctags? I can reproduce the issue with Universal Ctags, but not with Exuberant Ctags. So this looks like a bug in Universal Ctags to me.

Exuberant Ctags output:
```
$ ~/src/ctags/ctags/dctags -f - --language-force=c --format=2 --excmd=pattern --extra= --fields=nksaSmt test.c
AppHandler_RegisterSensor       test.c  /^static int AppHandler_RegisterSensor(void) {$/;"      f       line:9 signature:(void)
main    test.c  /^int main(int argc, char **argv) {$/;" f       line:1  signature:(int argc, char **argv)
```

Universal Ctags output:
```
$ ~/src/universal-ctags/ctags/ctags -f - --language-force=c --format=2 --excmd=pattern --extra= --fields=nksaSmt test.c
main    test.c  /^int main(int argc, char **argv) {$/;" f       line:1  typeref:typename:int    signature:(int argc,char ** argv)
```

**Comment by rjayatilleka** [comment]
Figured it out. Its not a bug but an API change (though I don't know why Universal made the change. I'll look into it later). The problem is the `--extra=<blank>` flag, which disables all the extra flags. The flags are

```
q - class-qualified entries
f - filename entries going to beginning of file
. - Universal only, filename entries going to end of file
p - Universal only, pseudo tags that include author, program info, etc
F - Universal only, equivalent to --file-scope
```

The problem is the `F` flag, which is equivalent to `--file-scope=[yes|no]`. That option is `yes` by default, which means objects visible only to that file, including C static functions, will be added to the tags. When extra is blank, that disables `F`, which sets `--file-scope=no`, so static functions won't be tagged.

Anyway, that's the root cause as far as I can tell. I'm not sure what the best way to proceed is. If tagbar can change the flags based on whether its universal or exuberant, it's probably easiest to just set the `--extra` flag separately. Otherwise, not so sure. @majutsushi Thoughts?

**Comment by rjayatilleka** [comment]
`universal-ctags --extra= --file-scope=yes` forces the file scope arg, so it works as desired. The actual easiest solution then is just to add the `--file-scope=yes` to the command, and that solves all the problems. I think that's the best. @majutsushi Is that okay with you?

**Comment by majutsushi** [comment]
Thanks for tracking this down! I've added the --file-scope argument now, so
everything should hopefully work.
