### ISSUE TITLE
C++11 override specifier incorrectly parsed

### ISSUE THREAD

**Issue by lepricon** [majutsushi/tagbar#318]
All member functions marked with `override` specifier are not normally visible in TagBar list. There are only `+override` visible instead of function name.
CTags seems to parse them correctly since such functions can be located using CTags.

**Comment by majutsushi** [comment]
Exuberant Ctags doesn't actually parse them correctly, the reason it seems to work for you is probably that the line number is correct. The tag name isn't, though, and that's what Tagbar needs.
This issue is fixed in [Universal Ctags](https://ctags.io/) though, so I would recommend switching to that.
