### ISSUE TITLE
Airline font broken on inactive tagbar window after recent update

### ISSUE THREAD

**Issue by manasthakur** [majutsushi/tagbar#339]
Hi @majutsushi ,

I appreciate that updates to TagBar are coming again. However, a recent update broke the font glyph for powerline fonts in vim-airline, on an inactive tagbar window. Please see the screenshot (before the filename).
![screen shot 2016-09-14 at 10 09 58 am](https://cloud.githubusercontent.com/assets/5248710/18500265/a217d122-7a63-11e6-9469-1ef7fc79be51.png)

**Comment by majutsushi** [comment]
Hmm, I can't really imagine how one of the recent Tagbar updates caused this, especially since Tagbar doesn't handle the statusbar contents if you're using airline. Tagbar just passes some information to airline. The only statusline related recent change was to update it a bit more often. My suspicion would rather be that it's a change either in airline or something else in your environment that changed.

**Comment by manasthakur** [comment]
Yes, I am discussing it over the airline page as well.
I guess this can be closed then.
