### ISSUE TITLE
Tagbar with Syntastic and Vim >= 7.4.2299 shows nothing

### ISSUE THREAD

**Issue by nattofriends** [majutsushi/tagbar#347]
When running Vim >= 7.4.2299 (https://github.com/vim/vim/commit/04c4ce650f9e533cd35b2aa6803f4d354d3ec7aa) and the latest versions of Tagbar and Syntastic, Tagbar shows no output in its window and the debug log doesn't show Tagbar running ctags at all. If the version of Vim is below 7.4.2299 or Syntastic is not present, the problem does not occur.

**Comment by jpmv27** [comment]
Relevant: https://groups.google.com/forum/#!topic/vim_dev/4GKEpx8bvzM

In that patch, vim now fires QuickFixCmdPre and QuickFixCmdPost autocmds on additional conditions

**Comment by gnujeremie** [comment]
Maybe the same issue as mine https://github.com/majutsushi/tagbar/issues/346

**Comment by nattofriends** [comment]
In the symptoms I have experienced no tag output is ever rendered.

**Comment by majutsushi** [comment]
Odd, I'm not able to reproduce this with just syntastic and Tagbar installed, and reading the thread that @jpmv27 linked I'm not quite clear how the Vim change could break Tagbar. The only thing Tagbar does in those autocommands is set a variable that essentially suspends Tagbar while a quickfix command is running. So the only way I could think of that would prevent Tagbar from working is if the `Post` command doesn't run, so Tagbar never resumes. I have no idea how this could happen, though.

However, I think this should still be easy to fix. The reason why Tagbar gets suspended during quickfix command execution is because the various `grep` commands have to load a file in order to search it, and if Tagbar would process each file loaded that way it would seriously slow things down (see #176 for the original bug report). So restricting the autocommand pattern to `*grep*` instead of just `*` should fix this issue without slowing things down again. Could someone who can reproduce the issue please try this pattern in the two `QuickFixCmdPre/Post` autocommands in the `CreateAutocommands()` function and see if it works? Thanks!

**Comment by nattofriends** [comment]
Hmm, I changed some unrelated parts of my Vim config recently and can no longer reproduce the issue any more either. Sorry :(

**Comment by majutsushi** [comment]
Weird. I've made the change regardless since it shouldn't break anything, and potentially prevent other issues. Let me know if the issue crops up again.
