### ISSUE TITLE
View of terminal changed when I quit vim since I update vim to 8

### ISSUE THREAD

**Issue by ExecutionHY** [majutsushi/tagbar#356]
If I quit Vim, the background color of terminal turns into something white...
And I know it has something to do with tagbar because the view won't have bugs if I delete this bundle. 
I've tried some version of your projects, all of them seem to have this problem.

![ea409359-93b8-47bf-bafb-b9d433fbf13f](https://cloud.githubusercontent.com/assets/23124748/19813837/05c99fde-9d6e-11e6-83c9-ee555ebb0121.png)

**Comment by majutsushi** [comment]
I can't really imagine that this is really caused by Tagbar. Tagbar doesn't do anything with the terminal, and doesn't do anything special with colours either. I suspect rather that there is a different underlying issue in your setup that gets exposed by Tagbar for some reason, like for example an incorrect `$TERM` setting.

**Comment by ExecutionY** [comment]
OK, I was just adding some bundles to vim according to some blogs, the bundles I have added are:
pathogen / NEROtree / Tagbar / ctags / ctrlp / vim-powerline / syntastic / supertab / Auto-pairs
And, actually I did't get such an awful result at the time I added Tagbar. 
Because of some bugs occur on syntastic, I update the vim by 
```
sudo brew install vim
```
and after the vim updated, this bug occurs. And I tried several times, delete tagbar, ok; add tagbar, bug occurs.

**Comment by majutsushi** [comment]
If this only started to happen after updating Vim then this only strenghtens
my suspicion that it is not a bug in Tagbar. Vim probably changed some
behaviour around terminal escape codes in the version that you updated to.

My best guess is still that this is caused by an incorrect $TERM setting, but
unfortunately I can't really help debug this since I don't have a Mac and
can't reproduce this.

**Comment by alerque** [comment]
As noted already this is almost certainly something to do with vim & the terminal, not tagbar. If there is any evidence to the contrary I'd be happy to re-open this issue to track a fix, but for now I don't think there is anything for us to go off of here. Did you ever get this figured out for yourself @ExecutionHY?
