### ISSUE TITLE
Tagbar interference during vimdiff

### ISSUE THREAD

**Issue by rohithvsm** [majutsushi/tagbar#358]
I have the following autocmds in my vimrc:
```
" Automatically open tagbar if you're opening vim with a supported file/files.
autocmd VimEnter * nested :call tagbar#autoopen(1)
" Automatically open tagbar while opening a supported file in an already
" running vim.
autocmd FileType * nested :call tagbar#autoopen(0)
" If you use multiple tabs and want Tagbar to also open in the current tab when
" you switch to an already loaded, supported buffer.
autocmd BufEnter * nested :call tagbar#autoopen(0)
```
When I run vimdiff on 2 source files, tagbar opens and it considers tagbar as one of the buffers and does a 3-way diff. TagbarClose does not help. How do I make sure Tagbar does not open when doing vimdiff? Thank you.

**Comment by majutsushi** [comment]
I added some code recently that skips a file if it has the window-local `diff` option set, but that doesn't work reliably when started as `vimdiff` since that option is set too late for some of the windows. You can however change your vimrc to only create the autocommands if Vim wasn't started as `vimdiff` by wrapping them in a test of that option:
```
if !&diff
    " autocommands
endif
```

**Comment by rohithvsm** [comment]
Thank you, that solves the problem for me. Thanks for your response and time.
