### ISSUE TITLE
Feature Request: Option Hide Variables

### ISSUE THREAD

**Issue by mlopezgva** [majutsushi/tagbar#363]
Hi!

Every time I show the tagbar, I end up foldening the "Variables" section, since I don't use it. Instead of editing the ctags config per language, could be possible to configure **tagbar** to hide or at least collapse the _Variables_ secion?

Thank you.

**Comment by majutsushi** [comment]
I don't think there's a good way to do this in general, since the definition of "variable" can be rather different between languages. You would at least need a kind of list that contains the "kinds" of each language that specifies variables, but then you would also invariably get disagreements between people exactly which "kinds" should be included in that. Globals? Locals? Constants? Statics? Macros? I think this has too many subjective and hard-to-define parts to make it really feasible for such a specific purpose.

**Comment by PezCoder** [comment]
@mlopezgva I had the same issue but this is what i did.
I noticed that whenever I open tagbar I'm mostly inside a function or some variables & gets positioned in variables section of the tagbar hence I changed my mapping to include a `-` after launching tagbar so it autocloses the variables section.
`nmap <leader>t :TagbarToggle<CR>-<CR>`
Not really a solution but works for me 😄
