### ISSUE TITLE
improvement: API for external control of Tagbar

### ISSUE THREAD

**Issue by gasparch** [majutsushi/tagbar#379]
I need your opinion, @majutsushi :)

I'm trying to put together perfect setup for Elixir development (but also for other languages as well), so I tried to integrate tagbar and ctrl-p. Goal is to have quick fuzzy search through the functions/modules/etc list w/o implementing fuzzy search and all tag support myself :)

Can you please check this commit ? https://github.com/majutsushi/tagbar/commit/3f95b34245f728c3948f31d6a377949d6d282672
It adds two functions for interacting w/tagbar.
 - getting list of current tags
 - jumping to specified tag

Here is the [plugin](https://github.com/gasparch/ctrlp-tagbar.vim) which uses it for integrating w/ctrl-p (you do not need any patching on ctrl-p side).
To enable this extension you need to add it to ctrl-p too.
```vim
let g:ctrlp_extensions = ['tagbar']
```

Can you check if this patch is ok? If yes - I'll create PR. If not - I'll maintain forked version, but that generally means more pain :)

**Comment by majutsushi** [comment]
I see you've integrated this commit in your other pull request. I think similar to what I said about the other changes there I would like to think about an API a bit more. Especially since I've also been wanting (for quite some time now) to extract all of the ctags parsing into a separate library with a useful API, so that other plugins can make use of it and you don't have to configure your types for each plugin separately. I'm not sure yet how soon I'll have something working, though. But I definitely want to include things like these.

So since this is already part of the pull request I'm going to close this issue to avoid confusion. Thanks for all your work!

**Comment by gasparch** [comment]
okay. so forking is my friend :))) feel free to message me if you need some help with implementation/adding tests/etc, because it is impossible to build decent IDE-looking environment without plugins such yours. And writing all that from scratch will be huge waste of time :) And I'm slowly progressing towards creating nice environment for Elixir :)

Actually after having tagbar+ctlr-p working together I rarely open tagbar ;) only to explore the code. but for jumping around I mostly use ctrlp search.
