### ISSUE TITLE
[wish-list] Use Asynchronous Jobs in Vim 8 to Update Tags in Background

### ISSUE THREAD

**Issue by skywind3000** [majutsushi/tagbar#381]
Tagbar is a great plugin, but still not so perfect (comparing to similar function in IDEs or Emacs):
Vim always get unresponsive for a noticable period when I'm opening/editing big files with tagbar running.
It would be very nice if tagbar can refresh in background when I am using Vim 8.

**Comment by majutsushi** [comment]
Unfortunately the asynchronous features in Vim 8 wouldn't help here. The slowest part of processing a big file is not the external job, but the parsing of the output into a tree structure within Vim, and Vim's own functions cannot be run asynchronously due to Vim's inherent single-threaded nature. The only thing that might help would be to reimplement that part in for example Python and use that language's threads. But that would be a significant refactoring, so I'm not sure when I would get around to doing that. It's certainly something I thought about before myself, though.

**Comment by skywind3000** [comment]
TagBar doesn't need a background thread to analyse tags, there is a much simple way to prevent stuck which doesn't require python 2/3 threading:

You can apply an Incremental Analysing:

Divide the whole processing job into pieces, and put them in timers (eg, a 20Hz interval), analyse fixed amount of tags in an interval than refresh the tagbar after all pieces are finished and stop the timer.

User can config how many tags need to be processed in an interval

In this way, vim will never get stucked and tagbar can work perfectly without a python 2/3 thread.

**Comment by skywind3000** [comment]
Big refactor is not required and many code could be reused.

**Comment by majutsushi** [comment]
This would actually have required a big refactoring since the previous algorithm didn't work tag-by-tag. I also don't think an incremental updating would have been such a good idea since a user couldn't really be sure whether the current display was up-to-date or whether there were more incremental updates forthcoming. I instead went a different route to implement some optimizations.
