### ISSUE TITLE
tagbar empty when using ctags with parameter: --extra=q

### ISSUE THREAD

**Issue by Jeansen** [majutsushi/tagbar#391]
I have the following setup:

```
let g:tagbar_type_perl = {
    \ 'ctagstype'   : 'Perl',
    \ 'kinds' : [
        \ 'p:packages:1:0',
        \ 'c:constants:1:0',
        \ 'f:formats:1:0',
        \ 's:subroutines:1:0',
    \ ],
\ 'ctagsbin'  : 'ctags',
\ 'ctagsargs' : '--extra=q' 
\ }
```

This gives me an empty tagbar. ;-( Without the last line `\ 'ctagsargs' : '--extra=q' ` it works. Is this an expected behavior or am I missing something?

**Comment by majutsushi** [comment]
If the `ctagsargs` option is specified then its contents are the only arguments that are passed to the executable specified with the `ctagsbin` option, so all the arguments that would normally get passed to ctags are missing in your case. Specifying the `q` extra argument wouldn't actually be very useful in any case since you would end up with duplicate tags. It would be better to improve the perl parser in [Universal Ctags](https://ctags.io) to properly report scopes, otherwise you won't get a nice Tagbar display even with the `q` argument.

If you really do want to make use of that flag you will have to put all of the arguments that ctags needs into that option. Have a look at the `s:ExecuteCtagsOnFile()` function for what Tagbar normally passes to ctags.

**Comment by Jeansen** [comment]
Thank's for the quick answer! Could you post the default option string for ctagsargs that is used for Perl? I had a look at `s:ExecuteCtagsOnFile` and I am very familiar with Vim-Script (yet).  This would help alot. Anyway I tried this, but it did not work, so far:
```
\ 'ctagsargs' : [
\'-f',
\ '-',
\ '--format=2',
\ '--excmd=pattern',
\ '--fields=nksSaf',
\ '--extra=',
\ '--file-scope=yes',
\ '--sort=no',
\ '--append=no',
\ '--language-force=Perl'
\ ]
```
I am aware that something is missing for "kinds". But I am not sure what to put there. So, maybe you could post a string that should work or give me a hint how to debug it and see for myself?
