### ISSUE TITLE
vim force to suspend while use tagbar

### ISSUE THREAD

**Issue by int32bit** [majutsushi/tagbar#392]
Recently I updated my `tagbar` plugin from master branch and I found that my vim force to suspend once I call `TagbarToggle` . The terminal output looks like these:

```
[1]  + 76946 suspended (tty output)  vim vimrc
``` 

This issue seems reproduce 100%. I'm really not sure if my configuration is something wrong. Here is my vimrc:

```
Plugin 'majutsushi/tagbar'
...
let tagbar_left=1
nnoremap <Leader>t :TagbarToggle<CR>
let tagbar_width=32
let g:tagbar_compact=1
```

Thanks for any help!

**Comment by majutsushi** [comment]
It's highly unlikely that this is actually caused by Tagbar itself, and based on the information you provided I can't really make a good guess as to what is going on. I would recommend experimenting with your configuration to see if you can narrow down the cause. The only idea I have is that it may have something to do with calling `system()` in Vim, you could try what happens if you call that manually with something like `ls`. But there's probably some involvement from your terminal, tmux and/or shell config.

**Comment by int32bit** [comment]
I dug into my configuration, and I found I set shell in my `vimrc` like `set shell=bash\ -i`. After remove this, it works well. So I 'm sure it's not a bug related to this plugin. Sorry for that.
