### ISSUE TITLE
Error: undefined variable parent

### ISSUE THREAD

**Issue by datanoise** [majutsushi/tagbar#396]
https://github.com/majutsushi/tagbar/blob/master/autoload/tagbar.vim#L2672

**Comment by majutsushi** [comment]
Some information about how to reproduce this issue would be helpful ...

**Comment by datanoise** [comment]
i get an error every time I open any golang source code. But for the starter, there is no `parent` local variable in this scope and function parameters must be prefixed with `a:`

**Comment by majutsushi** [comment]
There are several places where that variable should have been set in the
function, but apparently it's not happening in your case.

What are you using for Go support?

**Comment by datanoise** [comment]
i've using `fatih/vim-go` and the following ctags definition:

```
--langdef=Go
--langmap=Go:.go
--regex-Go=/func([ \t]+\([^)]+\))?[ \t]+([a-zA-Z0-9_]+)/\2/f,func/
--regex-Go=/var[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/v,var/
--regex-Go=/type[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/t,type/
```

**Comment by majutsushi** [comment]
There seems to be something odd about your setup. I've had a look at that `vim-go` project, and it is set up to use the `gotags` program instead of regular ctags, so the ctags definition you posted above would not have been used.

I've given the above project a try together with the `gotags` parser, and it worked fine for me. So I wonder what's different for you. Could you please use the debug mode as described in `:h tagbar-issues` and upload both of the generated logfiles somewhere if possible? Thanks.

**Comment by majutsushi** [comment]
Oh, and please update Tagbar before you do that since I just expanded the debugging functionality a bit.

**Comment by datanoise** [comment]
Actually, I was incorrect saying that I get this error message on any Go file. It turned out that only this one from Go project that gives me this error:
https://github.com/golang/go/blob/master/src/net/http/server.go

Can you try opening it and see if you can reproduce?

**Comment by datanoise** [comment]
Also you are right. I posted my ctags config without realizing that vim-go has a special treatment for your plugin. Sorry for the confusion.

**Comment by majutsushi** [comment]
Thanks, I was able to reproduce it now. I've just pushed a commit that should fix it.
