### ISSUE TITLE
currenttag and nested python functions

### ISSUE THREAD

**Issue by muffinmad** [majutsushi/tagbar#399]
Example code:
```python
def function1(x):
    def function2(y):
        pass
    for z in x:
        pass
```
With cursor on line 4 (```for z in x:```) the result of calling ```tagbar#currenttag('%s', '', 'f')``` is ```function1.function2``` but it must be just ```function1```

**Comment by majutsushi** [comment]
I could have sworn I replied to this issue, but apparently not, sorry.

Unfortunately this is impossible to solve from within Tagbar since ctags only reports the tag where a function starts, but nothing about where a function ends. So Tagbar uses a heuristic to assume that the closest function tag above the current position is the current function. This is obviously not perfect, but works okay for most cases. In order to fix this issue ctags would have to report more information about a function, which then could be made use of in Tagbar. I suggest opening an issue on the Universal Ctags bug tracker.

**Comment by jasontibbitts** [comment]
I've also had the same issue, so I decided to dig into it a bit.  Universal Ctags does actually support this functionality.  I'm not sure when it was added, but randomly clicking around their repository shows that it's been there since 2016 at least.

If you ask for the 'e' field, it will indicate the lines on which when functions end.  So given this code:
```
def a():
    def b():
        pass

    def c():
        pass

    # Should just be in a.
    pass
```
and this command (which differs from what tagbar executes only by the addition of the 'e' field):
```
ctags --format=2 --excmd=pattern --fields=nksSafe --extra= --file-scope=yes --sort=no --append=no -V --language-force=python --python-kinds=icfmv -o - ~/foo.py
```
I get the following:
```
ctags: Warning: --extra option is obsolete; use --extras instead
  Option: --language-force=python
  Option: --python-kinds=icfmv
Initialize parser: Python
  Option: -o -
Reading command line arguments
OPENING /home/tibbs/foo.py as Python language file [new]
a       /home/tibbs/foo.py      /^def a():$/;"  f       line:1  access:public   signature:()    end:9
b       /home/tibbs/foo.py      /^    def b():$/;"      f       line:2  function:a      file:   access:private  signature:()    end:3
c       /home/tibbs/foo.py      /^    def c():$/;"      f       line:5  function:a      file:   access:private  signature:()    end:6
```
Without the 'e' flag I just get:
```
ctags: Warning: --extra option is obsolete; use --extras instead
  Option: --language-force=python
  Option: --python-kinds=icfmv
Initialize parser: Python
  Option: -o -
Reading command line arguments
OPENING /home/tibbs/foo.py as Python language file [new]
a       /home/tibbs/foo.py      /^def a():$/;"  f       line:1  access:public   signature:()
b       /home/tibbs/foo.py      /^    def b():$/;"      f       line:2  function:a      file:   access:private  signature:()
c       /home/tibbs/foo.py      /^    def c():$/;"      f       line:5  function:a      file:   access:private  signature:()
```

Now, I have no idea at all how difficult it would be to get Tagbar to actually parse and use the 'end' field, but at least the data is there.

**Comment by wookayin** [comment]
This is unfortunately a limitation of tagbar. I know this might be an off-topic, but for those who might find this issue by Googling:

If you are looking for how to workaround this using different plugins (e.g. *using LSP*), one can use:

- https://github.com/tyru/current-func-info.vim
- universal: https://github.com/liuchengxu/vista.vim (Use `b:vista_nearest_method_or_function`)
- universal: LSP (coc.nvim's action [getCurrentFunctionSymbol](https://github.com/neoclide/coc.nvim/pull/679))

**Comment by alerque** [comment]
Very interesting find @jasontibbitts, and thanks for those links @wookayin. I would be quite happy to see tagbar support end tags properly (for supported languages of course). If anybody wants to work on it we would gladly help review and merge any good PRs. I would actually re-open this issue, but it seems like #508 is basically a duplicate.
