### ISSUE TITLE
Please support Neovim in Windows

### ISSUE THREAD

**Issue by rmolin88** [majutsushi/tagbar#405]
- Error message after running Tagbar:
```
Error detected while processing function tagbar#ToggleWindow[1]..<SNR>97_ToggleWindow[9]..<SNR>97_OpenWindow[25]..<SNR>97_Init[4]..<SNR>97_CheckForExCtags[64]..<SNR>97_CtagsErrMsg:
line   10:
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
GNU ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "ctags --version"
Command output:
'\"ctags --version\"' is not recognized as an internal or external command,
	operable program or batch file.
```
- This is probably a neovim bug as well but please keep it mind for future support. Neovim full support for windows is very near.
- BTW:
```vim
echo system('ctags --version')
```
```
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
Compiled: Jul  9 2009, 17:05:35
Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
Optional compiled features: +win32, +regex, +internal-sort
```

**Comment by sphynx79** [comment]
I have solved this problem in windows, edit file autoload\tagbar.vim

comment line 3882:
set shellxquote=\" => " set shellxquote=\"
  
edit line line 3893:
system(a:ctags_cmd) => system(substitute(a:ctags_cmd,"'", "","g"))

**Comment by majutsushi** [comment]
As @rmolin88 suspected this seems to be a bug in Neovim: https://github.com/neovim/neovim/issues/6329, https://github.com/neovim/neovim/pull/6359

Since Windows support is still considered experimental in Neovim I'd rather not add workarounds for temporary bugs that may stop working once the bugs are fixed, but I'll definitely have a look once it's officially supported.
