### ISSUE TITLE
universal-ctags with restructured text

### ISSUE THREAD

**Issue by haizaar** [majutsushi/tagbar#408]
Good day,

universal-ctags has now built-in support for restructured text and I'm trying to figure out how to use it (instead of rst2ctags). What I'm struggling with is to display doc hierarchy properly and getting this instead:
![image](https://cloud.githubusercontent.com/assets/58201/24150808/84b0f0de-0e4f-11e7-8449-a26835f92666.png)

Here is what I've tried to define (followed Python defs in code and rst example in Wiki):

.vimrc:
```
let g:tagbar_type_rst = {
    \ 'ctagstype' : 'reStructuredText',
    \ 'kinds'     : [
        \ 'c:chapters',
        \ 's:sections',
        \ 'S:subsections',
        \ 't:subsubsections'
    \ ],
    \ 'kind2scope' : {
        \ 'c' : 'chapter',
        \ 's' : 'section',
        \ 'S' : 'subsection',
        \ 't' : 'subsubsection',
    \ },
    \ 'sro' : '|',
    \ 'scope2kind' : {
        \ 'chapter' : 'c',
        \ 'section' : 's',
    \ },
    \ 'sort': 0,
\ }
```

The rst file:
```
***
foo
***
asdf

section 1
=========
asdf

subsection 1
------------
asdf

bar
~~~

section 2
=========

subsection 2
------------
```

And here is what ctags generate:
```
ctags -f - --format=2 --excmd=pattern --fields=nksSaf --extra= --file-scope=yes --sort=no --append=no --language-force=reStructuredText --reStructuredText-kinds=csSt /tmp/my.rst 
ctags: Warning: --extra option is obsolete; use --extras instead
foo	/tmp/my.rst	/^foo$/;"	c	line:3
section 1	/tmp/my.rst	/^section 1$/;"	s	line:7	chapter:foo
subsection 1	/tmp/my.rst	/^subsection 1$/;"	S	line:11	section:section 1
bar	/tmp/my.rst	/^bar$/;"	t	line:15	subsection:subsection 1
section 2	/tmp/my.rst	/^section 2$/;"	s	line:18	chapter:foo
subsection 2	/tmp/my.rst	/^subsection 2$/;"	S	line:21	section:section 2
```

For Python they generate pretty similar structure and can't find what am I missing in configuration.
Can anyone please help?

**Comment by haizaar** [comment]
Bump.

**Comment by majutsushi** [comment]
Hi, sorry for the late reply. The reason for the incorrect display is that the ctags output is incorrect. For the subsections it reports the scope as `section:section 1`, but it should instead report the full path of the section including the chapter name. This is for two reasons: 1), this is what all other parsers do and thus how Tagbar expects the output to be, and 2), without the full path the scope name is potentially ambiguous.

Unfortunately RestructuredText doesn't have a "scope resolution operator" like `.` in many programming languages, so it is not clear what the complete path should look like. I improved the LaTeX parser in ctags a few years ago and had to introduce the "fake" operator `""` in order to make this work, maybe the RST parser could do something similar. That is something you would have to take up with the Universal Ctags developers.
