### ISSUE TITLE
Vim 7.3 Unknown function: s:createKinddict

### ISSUE THREAD

**Issue by nelsyeung** [majutsushi/tagbar#442]
I'm getting this error for Vim 7.3:

```
Error detected while processing function tagbar#ToggleWindow..<SNR>151_ToggleWindow..<SNR>151_OpenWindow..<SNR>151_Init..<SNR>151_InitTy
pes..tagbar#types#ctags#init:
line  743:
E117: Unknown function: s:createKinddict
```

No errors for Vim 7.4+.
I believe this is caused by: 460f3c8f2eb2e80a0109f6c40599502ee8a9303c

**Comment by majutsushi** [comment]
This is due to a bug in Vim that was fixed in version 7.3.1058. The new behaviour in Tagbar offers various advantages, and unfortunately it's not really feasible to have both behaviours available for backwards compatibility. Since the bug was fixed over four years ago I'm inclined to say that you should either upgrade your Vim or just stick with an older version of Tagbar in that Vim installation.

**Comment by nelsyeung** [comment]
Ah, I thought it's something like this. Is it possible to add such version requirement to the README so that people would know? It's unfortunate that I'm unable to update vim as it's a university machine, I'll just revert tagbar back. Thanks.

**Comment by majutsushi** [comment]
You're right, I'm going to add it to the README. When making the change I wasn't aware that this bug existed in older versions so I didn't think it was necessary.

**Comment by Grazfather** [comment]
For others with this issue, you can fix it with vim plug:

`Plug 'majutsushi/tagbar', { 'commit': 'd4a08c33e516314f35c541b34fe7f909c2ff4381' }`

**Comment by yzsatgithub** [comment]
upgrade vim will solve the problem.
