### ISSUE TITLE
Missing space after foldermarker when tagbar_show_visibility = 0

### ISSUE THREAD

**Issue by hanschen** [majutsushi/tagbar#462]
Using `let g:tagbar_show_visibility = 0` removes the space between the foldmarker and the following text, so instead of e.g. `▼ variables` you get `▼variables`.

Looking at the code it seems intentional, but I don't see why.

https://github.com/majutsushi/tagbar/blob/c004652797185121bbf264138d57eb2a0199b6db/autoload/tagbar.vim#L1716

**Comment by majutsushi** [comment]
That's just to save space, so that in cramped terminal you can display more of the actual tag name. If there's a space instead of a visibility symbol between the fold marker and the tag name it means that visibility  info is turned on, but ctags didn't provide visibility information for that specific tag. So that space is just there to make the display look consistent in case some tags have visibility information and some don't.

**Comment by hanschen** [comment]
I see, thank you for the explanation. I happen to like the space after `▶` `▼` so I added the following to my .vimrc:

    let g:tagbar_iconchars = ['▶ ', '▼ ']
