### ISSUE TITLE
how to hide anonymous function ? 

### ISSUE THREAD

**Issue by pingsoli** [majutsushi/tagbar#474]
I think, ctags does some parsing jobs, and tagbar decide what to show(I don't know if it is right, but don't care). Lambda expression will be marked as annoymous function, I really want to hide the anonymous function info in tagbar window, what can I do ?

![image](https://user-images.githubusercontent.com/15207838/35469615-70c59664-0373-11e8-833b-d7f0594a86ab.png)

lambda expression is everywhere, showed in tabbar is some kind of annoying. I'll appreciate your reply.

**Comment by alerque** [comment]
I believe this is caused by the old parser in exuberant ctags. Please switch to universal ctags which has much improved parsing an options.

If just switching doesn't do it by default please report back here. There are some options to set for what kind of things you do/don't want to include, but I think the defaults may work for you after the switch. I'll be happy to re-open this if not.
