### ISSUE TITLE
Save .go files vim cursor will go to top of the file when opening tagbar.

### ISSUE THREAD

**Issue by hellodudu** [majutsushi/tagbar#486]
When saving go files with tagbar opened, The vim cursor will jump on top of the file and then jump back to the original position. Nothing happens when tagbar window is closed.

It's uncomfortable when using 'u' to undo things, The cursor will jump up and down.

vim8.0.
go1.9.2
![qq20180323-190321](https://user-images.githubusercontent.com/519830/37826073-1c83b5e2-2ecd-11e8-9098-52725bb31971.gif)

**Comment by rahmatismail** [comment]
I am facing the same problem
NVIM v0.2.2
Go 1.10.1 darwin/amd64

Also I use vim-go on neovim.
This only happened on write files, undoing changes works normally.

**Comment by toejough** [comment]
It's been almost a year since the last comment - has anyone found a way around this?

**Comment by alerque** [comment]
I'm not able to reproduce this personally, although clearly several of you are having the same problem. I would be happy to have a look if there were more details to try to reproduce, and more than happy to review a PR if somebody finds and fixes this. That being said I'm not a Go developer and unlikely to go hunting this down on my own spare time. If anybody does scratch this itch and get it fixed please do report back here about what the culprit was so we can get it fixed!

**Comment by alerque** [comment]
Is it possible this is not actually a tagbar issue but some other Go related plugin as turned out to be the case in #460?

**Comment by toejough** [comment]
It's not occurring for me at this moment... I don't know when it stopped happening, because this behavior was so disruptive that I'd stopped using tagbar.  

The cursor still blinks & pauses for half a second, but that doesn't really bother me.  I'm excited to be able to start using this sweet tool again!

If nothing changed in tagbar to address this, then it probably was some odd interaction, but I don't have the expertise to dig into it.

**Comment by alerque** [comment]
Hmm, that's interesting. I'm guessing this actually was a bad interaction with another Go related tool you all happen to have in common that got fixed from their end not ours. But before I close this it would be nice to have one more confirmation from somebody that had the problem in the first place; @hellodudu or @rahmatismail are either of you still able to replicate this?

**Comment by hellodudu** [comment]
Yes, sill can replicate this on latest vim-go and tagbar.
I believe it's caused by vim-go or gotags and I created a new issue here [https://github.com/jstemmer/gotags/issues/43](https://github.com/jstemmer/gotags/issues/43)

**Comment by alerque** [comment]
@hellodudu It's easy to "pass the buck", but given the feedback on the gotags issue I really do thing you should be looking into what `vim-go` is doing to your editor. Are you able to replicate this problem without it enabled? If so I'll try to come up with more steps to isolate this. If not I think this should be reported over there.

**Comment by hellodudu** [comment]
@alerque Yes, you're right. I can't replicate when vim-go is disabled. I'll step into it.

**Comment by hellodudu** [comment]
https://github.com/fatih/vim-go/pull/2621

This pr fixes, but have not merging yet. It's been tested for a while, and works fine.
Closing this and thanks for your help @alerque
