### ISSUE TITLE
Universal Ctags supports markdown natively

### ISSUE THREAD

**Issue by angelidis** [majutsushi/tagbar#489]
Latest version of Universal Ctags supports markdown natively.

When I try to use this with tagbar, it will not work.

See here:

https://github.com/universal-ctags/ctags/pull/1727

**Comment by weilbith** [comment]
@angelisdis did you have get it working?

**Comment by hupfdule** [comment]
I have prepared [a PR to support asciidoc](https://github.com/majutsushi/tagbar/pull/529). You could do the same for markdown.

See `:h tagbar-extend` for some info about the format of the configuration and how to call `ctags` to get the relevant info. Then add it to `tagbar/autoload/tagbar/types/uctags.vim`.

It is actually quite simple. Since markdown is very similar to asciidoc, it should be easy for you to prepare such a pull request when using mine as template.

**Comment by alerque** [comment]
Thanks again @aymanbagabas for the PR, this has been merged so this issue is complete.
