### ISSUE TITLE
Add support for Go (Exuberant CTags)

### ISSUE THREAD

**Issue by preslavmihaylov** [majutsushi/tagbar#536]
When I list the available languages of my ctags:
```
ctags --list-languages
```

there is an entry for the Go language. Also, I verified that ctags correctly generated a tags file for a go source file. However, tagbar doesn't seem to support golang.

When I open a go file and execute `TagbarToggle`, there is no tagbar generated for this source file.

**NOTE**: I am using Exuberant CTags, not Universal CTags. I noticed that there is support for Go by looking at `tagbar/types/uctags.vim`, but that is missing in `tagbar/types/ctags.vim`.

ctags version: Exuberant Ctags 5.9

**Comment by preslavmihaylov** [comment]
Was able to fix this by getting the golang-related code from `tagbar/types/uctags.vim` and pasting it into `tagbar/types/ctags.vim`.

Opened a PR: https://github.com/majutsushi/tagbar/pull/537

**Comment by butterflyfish** [comment]
gotags provide better output

**Comment by alerque** [comment]
I am closing this issue because support was merged in #537. That being said I am unfamiliar with Go language and its ecosystem. If, as @butterflyfish suggests, there is a better default tool to use for generating tags or better default options I would love to see them contributed here! Feel free to open another issue for this if you know there is something to be fixed, and even better open a PR if you know how to fix it.
