### ISSUE TITLE
My vim <leader> is “space“,It conflicts with "tagbar" shortcut.

### ISSUE THREAD

**Issue by yuanbi** [majutsushi/tagbar#546]
when open :TagbarToggle and focus it,  <leader > is invailed。

**Comment by butterflyfish** [comment]
my <leader> is <space>. I use "nmap <silent> t :TagbarOpenAutoClose<CR>"

**Comment by AndyMcAliley** [comment]
I had the same issue. Add the following line to your .vimrc:
```
let g:tagbar_map_showproto = "K"
```
Substitute any mapping you like in place of K. Then restart Vim (a quick ```:source %``` from the .vimrc file didn't do it for me). 

You can view all map option names from vim by typing 
```
:help tagbar-keys
```

**Comment by yuanbi** [comment]
> 我遇到过同样的问题。将以下行添加到您的.vimrc中：
> 
> ```
> let g:tagbar_map_showproto = "K"
> ```
> 
> 用您喜欢的任何映射代替K。然后重新启动Vim（`:source %`从.vimrc文件快速执行对我而言不是这样做）。
> 
> 您可以通过输入以下内容来查看vim中的所有映射选项名称：
> 
> ```
> :help tagbar-keys
> ```

vgbbbbbbbbbbbbbbbbbbn

**Comment by yuanbi** [comment]
> 我遇到过同样的问题。将以下行添加到您的.vimrc中：
> 
> ```
> let g:tagbar_map_showproto = "K"
> ```
> 
> 用您喜欢的任何映射代替K。然后重新启动Vim（`:source %`从.vimrc文件快速执行对我而言不是这样做）。
> 
> 您可以通过输入以下内容来查看vim中的所有映射选项名称：
> 
> ```
> :help tagbar-keys
> ```

thanks

**Comment by alerque** [comment]
Obviously the same key can't do two different things. Your choices are either to use a different leader or tell tagbar to use a different key.

Either way the solution seems to be presented here already, if you want to use space as a loader key, tell tagbar to use something besides space for it's show-protocol binding.

If there is anything else we can answer here let us know, but I'm closing the issue for now because it seems like this is resolved. It's also documented in the help file already.
