### ISSUE TITLE
Error in detecting ctags's version Universal/Exhuberant on MacOsX

### ISSUE THREAD

**Issue by JulienPivard** [majutsushi/tagbar#563]
When I run tagbar on a cpp file tagbar's section is empty. I run `:messages` in vim and I have this error :
```
Tagbar: Could not execute ctags for /Users/asmodee/Programmation/systeme_expert_0plus/src/client.cpp!
Executed command: "'/usr/local/bin/ctags' '--extras=' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=c++' '--c++-kinds=hdpgetncsufmv'
 '/var/folders/8j/gxtj_3hj6ydfdz4b8l2ybwqr0000gn/T/vMaZDzH/11.cpp'"
Command output:
ctags: Unknown option: --extras
Exit code: 1
```
My output when I run `ctags --version` is : 
```
Universal Ctags 0.0.0(1356570), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 13 2016, 12:29:58
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +multibyte, +option-directory, +coproc, +xpath
```
To solve the issue I change the line **510** in file **autoload/tagbar.vim** to : 
```vim
    if a:output =~? 'Universal Ctags' && a:output !~? 'Exuberant Ctags\s*\d\+\.\d\+'
```
but I don't know if this fix works for everyone or juste for me.

**Comment by JulienPivard** [comment]
Sorry my bad ctags and universal-ctags are installed both on my mac and link on ctags executable.

**Comment by alerque** [comment]
I don't understand why you ran into this error in the first place, the plugin should detect which version is active in your path. Even if you have both on your system, the one it detects and sets up the arguments for should also be the one it executes. How is it that got mixed up in your case?

**Comment by JulienPivard** [comment]
The link created by homebrew was not the right one, and universal-ctags was not in the path, there were only ctags.

**Comment by alerque** [comment]
I think my point still stands though. If Homebrew created a link to `ctags` and that was the only thing the plugin could find it should have detected and passed it compatible arguments that it could handle, not `universal-ctags` specific ones.

**Comment by JulienPivard** [comment]
Maybe a missing compilation option in my ctags version? The problem appeared after a homebrew update, so maybe a problem specific to this one?

**Comment by alerque** [comment]
The "exuberant" `ctags` project hasn't had a release in something like a decade. I just had a look at the [history](https://github.com/Homebrew/homebrew-core/commits/master/Formula/ctags.rb) (doesn't work on Github, you have to clone and do it locally) for the [Homebrew package](https://formulae.brew.sh/formula/ctags). There haven't been any major changes recently. They did move from an embedded patch to an [external one](https://github.com/Homebrew/formula-patches/blob/master/ctags/5.8.patch), but the update to the external one appears to be what had previously been embedded in the formula.

If the current Hombrew formula is packaging exuberant-ctags in such a way that we are detecting it as universal-ctags we do need to update our detection because that will affect a lot of people.

**Comment by JulienPivard** [comment]
I can try again to reinstall ctags and re-link it. But I don't know yet when I'll have time to try again.

**Comment by alerque** [comment]
No rush, but I just re-opened this issue so we don't loose track of it and just bury it with time. I don't care if it takes a while for you or somebody else to come along and test, but it would be useful to actually track down what the problem was and know that it's properly fixed and isn't just going to keep making trouble for other new users.

**Comment by JulienPivard** [comment]
After many tries I can't reproduce the probleme. I'll try again later if I come up with any more ideas.

**Comment by alerque** [comment]
Thanks for trying again. If even you can't replicate it I'm guessing something isn't what you thought it was and we can close this — but...

You weren't by chance using a non POSIX shell were you? Or have any Snap packages installed?

**Comment by JulienPivard** [comment]
I use zsh on macosX
```
$ zsh --version                                                     
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```
No snap package

**Comment by alerque** [comment]
Thanks again for the info @JulienPivard. I think I'll close this for now because there is nothing left for anybody to investigate.

If/when somebody comes along with the same or a similar issue hopefully a search will lead here and we can re-evaluate. I'll open this if there is a failure case we can poke at. Until then it's not really a "todo" item.
