### ISSUE TITLE
tagbar no longer recognizes ctags version on Windows

### ISSUE THREAD

**Issue by fwy** [majutsushi/tagbar#620]
After updating the tagbar plugin today on my Windows 10 machine, any attempt to run :TagbarToggle from vim 8.2 displays the following error.

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "ctags --version"
Command output:
Universal Ctags 0.0.0(7492b90e), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
Compiled: Nov 19 2019, 05:40:03
URL: https://ctags.io/
Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc
Exit code: 1
```

I believe the Universal Ctags version is fine, and it has not changed recently.  Also, the same plugin on the same machine works fine in neovim with no error.  On a separate Debian machine, it is also working fine both in vim and neovim.

In addition, if I execute :TagbarDebug, then run :TagbarToggle, it immediately starts working.  Afterwards if I run :TagbarDebugEnd, it continues working with no problem.

I am guessing that this problem was introduced in the latest commit for issue 611 (https://github.com/majutsushi/tagbar/pull/611), as this change includes conditional code that is run only on Windows and not in neovim.

**Comment by alerque** [comment]
What version of UCtags are you actually running? Can you paste a dump of the output of `:!ctags --version` so we can compare if the strings we are looking for are in there?

@skywind3000 Any ideas here?

**Comment by skywind3000** [comment]
try this:

```VimL
:let g:tagbar_python = 0
```

**Comment by fwy** [comment]
@alerque : the ctags version is in my previous post, but here it is again from :!ctags --version

Universal Ctags 0.0.0(7492b90e), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 19 2019, 05:40:03
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort,
  +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive,
  +yaml, +case-insensitive-filenames, +packcc

@skywind3000 : disabling g:tagbar_python seems to have fixed the problem, thanks!  Is that a permanent solution or just a temporary workaround?

**Comment by skywind3000** [comment]
uctags uses a new different format to represent file names on Windows:

- Exuberant compatible config:

    c:/users/name/hello.c

- Universal-ctags:

    c:\\users\\name\\hello.c

The new format sometimes even make vim crash when you press CTRL+].

A possible solution to this:

add a `--output-format=e-ctags` to uctags' when calling uctags.

**Comment by alerque** [comment]
Disabling the Python based launch method should be considered a temporary work-around. The out of the bog configuration should detect the ctags version correctly on Windows, and we seem to have broken that.

@skywind3000 I'm a bit confused how we seem to be capturing the output of `--version` correctly above even with the Python launcher turned on and yet disabling the launcher lets it run? I might have expected it to not capture the output at all, but this failure doesn't make sense to me yet. I'm somewhat reliant on you to help fix this though because I don't have Windows to test on.

Also, from your comment it sounds like adding a flag on Windows to get legacy path support is something we should do by default for `uctags`, no?

**Comment by fwy** [comment]
In case it helps: on my Windows 10 system I run msys2, and installed ctags from the msys2 package repositories.  Pathnames are generally delimited with forward slashes here, rather than the standard Windows backslash.

**Comment by skywind3000** [comment]
@fwy , I can't reproduce your problem, if you are working in msys2, the new python code should not be executed. vim's has('win32') in msys2 is 0.

**Comment by alerque** [comment]
@fwy When was the _last_ time you had updated? It was easy to jump to the conclusion that the latest Windows related change was what triggered this but it's looking more and more to me like it might be unrelated. If fact I wouldn't be surprised if it turns out to be something else on the system that changed.

Could you first `git checkout SHA` whatever revision you were using before the update you say broke this and confirm that the old version still works for you as you expect? Then if it does, checkout master again and run a `git bisect` starting at whatever version you confirmed works and find out what commit _actually_ broken this for you? That might enable us to narrow it down, but without being able to replicate it it's pretty hard to come up with a fix.

**Comment by fwy** [comment]
@skywind3000 , in my vim `has('win32')` is 1.  I don't run vim in msys2, it is a standard Windows build.  What I meant was that my ctags binary that is run from vim was obtained and installed through msys2.

@alerque , I update my vim plugins and msys2 packages routinely once a week, so I am sure that my last update included only changes released since a little over a week ago.  However, I understand that this problem might be caused by something more obscure in the environment, or some combination of this plugin and something else.  Over the next week I will try to downgrade and post the results.

**Comment by skywind3000** [comment]
Don't mix-up windows GVim and msys2 together. msys2 uses a different path schema:

    /c/program files/abc

Which is not recognized by windows vim and many plugins.

You should build/download a win32 uctags, which works fine with tagbar in my laptop.

try this one: https://github.com/skywind3000/support/blob/master/tools/ctags.exe

Or you can build a win32 uctags with mingw32.

**Comment by alerque** [comment]
I think @skywind3000 has it right here, the root issue is that you have mix and matched apps across dissimilar ecosystems. Win32 apps and msys2 apps and WSL apps etc. are not built to interact with each other. The file system path issues are just the start of the mess. Using both Vim & UCtags from the same ecosystem should work fine. It doesn't matter which you use, but don't mix and match. I don't think this plugin should be responsible for trying to paper over the differences, it is hard enough to support multiple platforms in the first place, supporting mixed environments where platform detection says one thing but some components behave differently because they are grafted in from somewhere else is just a nightmare proposition for us.
